### ISSUE TITLE
Access to API Groups

### ISSUE THREAD

**Issue by dmckillican** [kundk-ckret/homebridge-lightify-api#5]
Hi,

This is a great plugin you have developed here, although I'm coming up against an issue that I think this plugin is possibly able to resolve.

Most apps seem to only look at lights individually, as does Alexa and the homebridge-platform-lightify plugin

The issue for large Osram users such as myself is that I have 49 lamps, most of which are grouped in the Osram IOS app. For example, I have 6 GU10 PAR16 lightify bulbs in lighting my living room, and 4 in the kitchen, 4 in the office and so on.

all of the lightly plugins, including this one, turn each light on individually which is a really terrible experience when trying to contract a group of lights as main lighting. That said, the API does allow for the control of light groups defined in the Osram IOS app.

I have successfully controlled groups which then turn off/on in unison using the API, (e.g. https://us.lightify-api.org/lightify/services/group/set?idx=7&time=10&onoff=1), and having looked at your code, I think your plugin may be able to also do the same.

The issue is, I'm not a coder and I lack the skill to do this myself. Would it be at all possible to adjust the code to suit groups? If it were possible, this plugin would be way ahead of any other alternative I have found after months of research.

Anyway, just a thought - otherwise, good work!

**Comment by kundk-ckret** [comment]
hey

i think that would be possible, but the simple solution would be to group the lamps in homebridge or does that not work for you?

**Comment by kundk-ckret** [comment]
Groups can now be controlled. (At least on/off)
The fix will be in the 1.1.0 release

**Comment by dmckillican** [comment]
Hi!

Thanks for doing this - it works exactly as I had hoped. The only problem (Which is out of your control) is that the API has restrictions on the number of commands per minute. Therefore, dimming lights (which sends commends as your scroll up or down) causes the API to exceed almost immediately.

Otherwise, perfect thank you!!

**Comment by kundk-ckret** [comment]
Yep i know that.
I added throtteling (e.g. send only one update every half second) some time ago so the api doesnt get spammed, but in some cases even that is not enough. :(
